"""make changes in user model migration

Revision ID: 0549b494bc08
Revises: bd06ffb27c2d
Create Date: 2025-01-27 17:57:05.433665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0549b494bc08'
down_revision: Union[str, None] = 'bd06ffb27c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('BookAuthor_author_id_fkey', 'BookAuthor', type_='foreignkey')
    op.drop_constraint('BookAuthor_book_id_fkey', 'BookAuthor', type_='foreignkey')
    op.create_foreign_key(None, 'BookAuthor', 'author', ['author_id'], ['id'], source_schema='public')
    op.create_foreign_key(None, 'BookAuthor', 'book', ['book_id'], ['id'], source_schema='public')
    # Step 1: Add the column as nullable
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))

    # Step 2: Set a default value for existing rows
    op.execute("UPDATE \"user\" SET is_active = TRUE")  # Set all existing users to active

    # Step 3: Alter the column to be non-nullable
    op.alter_column('user', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_constraint(None, 'BookAuthor', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'BookAuthor', schema='public', type_='foreignkey')
    op.create_foreign_key('BookAuthor_book_id_fkey', 'BookAuthor', 'book', ['book_id'], ['id'])
    op.create_foreign_key('BookAuthor_author_id_fkey', 'BookAuthor', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###
