"""Change wallet_money_amount to Integer and enforce positive values

Revision ID: 8d881586fe6f
Revises: 0549b494bc08
Create Date: 2025-01-30 17:52:11.113186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d881586fe6f'
down_revision: Union[str, None] = '0549b494bc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('BookAuthor_book_id_fkey', 'BookAuthor', type_='foreignkey')
    op.drop_constraint('BookAuthor_author_id_fkey', 'BookAuthor', type_='foreignkey')
    op.create_foreign_key(None, 'BookAuthor', 'book', ['book_id'], ['id'], source_schema='public')
    op.create_foreign_key(None, 'BookAuthor', 'author', ['author_id'], ['id'], source_schema='public')
    op.alter_column('customer', 'wallet_money_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    op.execute('UPDATE customer SET wallet_money_amount = FLOOR(wallet_money_amount)')
    # op.create_check_constraint('check_wallet_positive', 'customer', 'wallet_money_amount >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_wallet_positive', 'customer', type_='check')

    op.alter_column('customer', 'wallet_money_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'BookAuthor', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'BookAuthor', schema='public', type_='foreignkey')
    op.create_foreign_key('BookAuthor_author_id_fkey', 'BookAuthor', 'author', ['author_id'], ['id'])
    op.create_foreign_key('BookAuthor_book_id_fkey', 'BookAuthor', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###
