"""Initial-1 migration

Revision ID: bd06ffb27c2d
Revises: 20cfa1d28e67
Create Date: 2025-01-26 21:13:16.182852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd06ffb27c2d'
down_revision: Union[str, None] = '20cfa1d28e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('BookAuthor_book_id_fkey', 'BookAuthor', type_='foreignkey')
    op.drop_constraint('BookAuthor_author_id_fkey', 'BookAuthor', type_='foreignkey')
    op.create_foreign_key(None, 'BookAuthor', 'author', ['author_id'], ['id'], source_schema='public')
    op.create_foreign_key(None, 'BookAuthor', 'book', ['book_id'], ['id'], source_schema='public')
    op.drop_column('user', 'wallet_money_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_money_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'BookAuthor', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'BookAuthor', schema='public', type_='foreignkey')
    op.create_foreign_key('BookAuthor_author_id_fkey', 'BookAuthor', 'author', ['author_id'], ['id'])
    op.create_foreign_key('BookAuthor_book_id_fkey', 'BookAuthor', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###
